config/routes.rb
Rails.application.routes.draw do
  resources :tags
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :topics
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  get 'comments/index'
  get 'comments/new'
  post '/comments', to: 'comments#create'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  # validates :tag, presence: true

  belongs_to :user
  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  has_many :comment_users, through: :comments, source: 'user'
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  def index
    @topics = Topic.all.includes(:favorite_users, :comment_users)
  end

  def new
    @topic = Topic.new
  end

  def show
  end

  def edit
  end

  def create
    @topic = current_user.topics.new(topic_params)
    # binding.pry
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to topics_path, success: '編集に成功しました'
    else
      render :edit
    end 
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topic_url, notice: "topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:user_id, :title, :image, :description, :tag)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= form_with(model: @topic, local: true) do |form| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, value: @topic.image %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <h2 class="topic-text">
              <%= topic.title %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
            <% else %>
                <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                  <%= image_tag 'icons/heart.png', class: 'topic-index-icon-red' %>
                <% end %>
            <% end %>

            <%= topic.favorite_users.count %>
            
            <%= link_to comments_new_path(topic_id: topic.id), remote: true do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>

            <p class="topic-text">
              <%= topic.description %>
            </p>
            
            <h2>コメント</h2>
            <div id=<%= "comment_new#{topic.id}" %>></div>            
              <p class="topic-text">
                <% topic.comments.each do |comment| %>
                  <p class="topic-text">
                  <%= comment.description %>
                  </p>
                <% end %>
              </p>          
            </div>
            <p class="topic-text">
             tags: <%= topic.tag %>
            </p>
            <% if topic.user.id == current_user.id %>
              <button class="btn btn-primary"><%= link_to '削除', topic, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <% end %>
          </div>
          <%= link_to '編集', edit_topic_path(id: topic.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :tag %>
            <%= f.collection_select :tag, Tag.all, :name, :name %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>